### ISSUE TITLE
feature: WAV files named with telephone numbers

### ISSUE THREAD

**Issue by duffy6** [jpluimers/fritzcap#18]
Hi!

Would it be possible to implement the new feature:

I would be nice to habe the WAV and the CAP files named like the telephone numbers.
For example: "calling person" (555-111) calls "called person" (555-222):

corresponding filename: 555-111__-__555-222____LENGTH_in_MINUTES.WAV 

duffy6

**Comment by jpluimers** [comment]
I think that's already covered in this open issue: https://github.com/jpluimers/fritzcap/issues/13

If you agree, then please close #18.

**Comment by duffy6** [comment]
Agreed :-)
