### ISSUE TITLE
Error  line 39

### ISSUE THREAD

**Issue by MZVOL** [jpluimers/fritzcap#20]
hello
i've install the master from https://github.com/jpluimers/fritzcap/archive/master.zip
and the Latest Python 3 Release - Python 3.6.4

and there is only

C:\fritzcap-master>fritzcap.py –capture_files –decode_files –monitor_calls —
box_name 192.168.179.1 —xxxxxxxxx PASSWORT
Traceback (most recent call last):
File „C:\fritzcap-master\fritzcap.py“, line 39, in
import argparse
ModuleNotFoundError: No module named ‚ConfigParser‘

please can you help me?

**Comment by jpluimers** [comment]
I've not tested this with Python 3.x yet, but it looks like for Python 3.x, `ConfigParser` got renamed to `configparser`: https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser/14087705#14087705 as I found searching for ["ModuleNotFoundError: No module named ‚ConfigParser"](https://www.google.com/search?q="ModuleNotFoundError%3A%20No%20module%20named%20‚ConfigParser")

Could you try running with Python 2.x?

**Comment by MZVOL** [comment]
it works with Phyton 2.7.14 (64-bit)
thank you

**Comment by jpluimers** [comment]
Closed because solved.
