### ISSUE TITLE
No valid CAP file captured - filesize 0

### ISSUE THREAD

**Issue by BernieHD** [jpluimers/fritzcap#22]
I've just installed Fritzcap and started to use it to record selected phone calls.

Here is what happens:

`E:\FritzBox7272\fritzcap-master>fritzcap.py --capture_files --decode_files --monitor_calls --box_name 192.168.178.1 --password foobar`
`2018-05-15 17:58:51,378 - FritzCap version 2.3.1 started.`
`2018-05-15 17:58:51,381 - Connect    to the call monitor service on fritzbox2:1012.`
`2018-05-15 17:58:51,390 - Connected  to the call monitor service on fritzbox2:1012.`
`2018-05-15 17:59:03,808 - Call       (ID:1, ActiveCalls.:1, Caller:6, DialedNumber:0123738487253, LinePort:SIP3)`
`2018-05-15 17:59:06,522 - Start capture (capture_file:'captures/2018-05-15/175906/capture_20180515175906.cap').`
`2018-05-15 17:59:09,588 - Connect    (ID:1, ActiveCalls.:1, Caller:6, DialedNumber:0123738487253, LinePort:SIP3)`
`2018-05-15 17:59:27,924 - Disconnect (ID:1, ActiveCalls.:0, Caller:6, DialedNumber:0123738487253, LinePort:SIP3)`
`2018-05-15 17:59:39,490 - Capture finished (capture_file:'captures/2018-05-15/175906/capture_20180515175906.cap').`
`2018-05-15 17:59:39,490 - Decode process started  (worker_id:1, file:'captures/2018-05-15/175906/capture_20180515175906.cap')`
**`2018-05-15 17:59:39,492 - Seems, there is no valid PCAP file`**
`2018-05-15 17:59:39,493 - Decode process finished (worker_id:1, file:'captures/2018-05-15/175906/capture_20180515175906.cap')`
`2018-05-15 18:00:42,930 - Connection to the call monitor service on fritzbox2:1012 stopped.`
`2018-05-15 18:00:42,936 - FritzCap version 2.3.1 finished.`

The listing of the captured file reads

`E:\FritzBox7272\fritzcap-master\captures\2018-05-15\175906>dir`
` Datenträger in Laufwerk E: ist Data1`
` Volumeseriennummer: BD0B-48E0`
` Verzeichnis von E:\FritzBox7272\fritzcap-master\captures\2018-05-15\175906`
`15.05.2018  17:59    <DIR>          .`
`15.05.2018  17:59    <DIR>          ..`
**`15.05.2018  17:59                 0 capture_20180515175906.cap`**
**`               1 Datei(en),              0 Bytes`**
`               2 Verzeichnis(se), 66.667.581.440 Bytes frei`
`E:\FritzBox7272\fritzcap-master\captures\2018-05-15\175906>`

FritzBox is Fritz!Box7272 with Fritz!OS 06.83

Any idea, what goes wrong and how to fix it?

**Comment by jpluimers** [comment]
No problem @BernieHD: I have a similar thing on a Fritz!Box 7390 that is configured as switch. I just answered in https://github.com/jpluimers/fritzcap/issues/21 that I had to use interface `1-lan`.

I made a rudimentary interface table at https://github.com/jpluimers/fritzcap/blob/master/fritzcap-interfaces-table.md, so if you have information to update that table, please let me know in a comment.
